### ISSUE TITLE
Add Privacy Policy, Terms of Service, and About Us to the website

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#398]
Add Privacy Policy, Terms of Service, and About Us to the website.

I have added all of these in the dashboard but they are not reflected on the website.

**Comment by technicalbirdVayuz** [comment]
Updated on Production Web. Pls check

**Comment by stevekamps** [comment]
on the About section please change to "North America's Premier Volleyball Community"

- Remove "we believe that every volleyball Athlete in North America should have an opportunity to be recruited to Clubs and Colleges. 

- AMateur Sports Unite LLC - Terms of Service appears 2 times at the top of the document when you click on it

- I have fixed some of the spacing etc in the Terms of Reference and Priviacy policy in the dashboard. Please update these changes to volleyballunite.com
-

**Comment by technicalbirdVayuz** [comment]
on the About section please change to "North America's Premier Volleyball Community"

- Remove "we believe that every volleyball Athlete in North America should have an opportunity to be recruited to Clubs and Colleges.
![image](https://user-images.githubusercontent.com/18699624/151304983-c7ec4dc0-6ff4-482e-ae0b-471d0b858ffe.png)

 
- AMateur Sports Unite LLC - Terms of Service appears 2 times at the top of the document when you click on it (Done)
- I have fixed some of the spacing etc in the Terms of Reference and Priviacy policy in the dashboard. Please update these changes to volleyballunite.com (Made both website & heroku content same)


Also, Please check changes on Heroku as of now, once checked & closed, we will update the build on production

**Comment by rgnarok** [comment]
Done please put it on live once done we will close this

**Comment by stevekamps** [comment]
1.  On the About page make the font exactly how it appears on the homepage of volleyballunite.com  (North America's Premier Volleyball Community)
2. The Privacy policy and Terms of reference still have some spacing issues. I fixed these in the dashboard last week but the changes are not reflective 
3. make the flag gifs transparent so we don't see white in the background . if you cant do this then send me the flags and I will  outsource someone else to fix this

**Comment by technicalbirdVayuz** [comment]
- On the About page make the font exactly how it appears on the homepage of volleyballunite.com (North America's Premier Volleyball Community)  @vayuzpriya Please check & update

- The Privacy policy and Terms of reference still have some spacing issues. I fixed these in the dashboard last week but the changes are not reflective - @stevekamps  Please share the content on Doc

- make the flag gifs transparent so we don't see white in the background. if you cant do this then send me the flags and I will outsource someone else to fix this - #399 (Keeping the discussion there only)

**Comment by stevekamps** [comment]
I have made the changes of Privacy policy and about us in the dashboard.  I want the spacinh to be consistent on the volleyballunite.com website ASAP

- Here re some GIF images to try. I played around with some software to make background transparent. Not sure if any of them will work but here they are
-
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/77851393/151583769-a118e258-5fc3-4252-aa1c-fc427b9f55e1.gif)
![ezgif com-gif-maker (10)](https://user-images.githubusercontent.com/77851393/151583782-a103ff1d-0acb-4b06-80cf-5a54982e7b9b.gif)
![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/77851393/151583806-e1f1c661-ddf1-4ddc-b6d6-033f934eb4e4.gif)
![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/77851393/151583810-1f0e4f37-c3b9-4bf6-9e0e-364bc6c57be9.gif)



![ezgif com-gif-maker (2)](https://
![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/77851393/151583799-2af2c1c6-786a-4b33-a523-02068565af3a.gif)
user-images
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/77851393/151583795-bdbbe01f-3106-4543-a215-5b51a4034b4b.gif)
.githubusercontent.com/77851393/15158378
![ezgif com-gif-maker](https://user-images.githubusercontent.com/77851393/151583836-29b6fe6c-5820-4151-aae1-4977087bdb2e.gif)

![ezgif com-gif-maker (9)](https://user-images.githubusercontent.com/77851393/151583828-274c5968-9b8a-47a0-b07c-b55ad0841636.gif)
8-f0457688-a567-4421-90ca-715e32e5ae1f.gif)
![ezgif com-gif-maker (8)](https://user-images.githubusercontent.com/77851393/151583822-b39e83cc-4714-4bed-a730-d2c07e56b4dc.gif)

**Comment by technicalbirdVayuz** [comment]
WE have updated it please check @stevekamps

**Comment by stevekamps** [comment]
![aboutus](https://user-images.githubusercontent.com/77851393/151584950-d3ef0a5e-9da7-4f9d-9926-b27195cf66aa.jpg)
![homepage](https://user-images.githubusercontent.com/77851393/151584956-97fbde99-59e2-4c50-a60f-69b9f2afd0af.jpg)

**Comment by stevekamps** [comment]
We need the About us to look like the homepage.  As you can see they are different

**Comment by stevekamps** [comment]
![IMG_9975](https://user-images.githubusercontent.com/77851393/151586270-10d70173-7d9a-42d7-a804-4438835c0186.jpg)

**Comment by stevekamps** [comment]
remove space

**Comment by stevekamps** [comment]
![IMG_9974](https://user-images.githubusercontent.com/77851393/151586329-d7005474-9782-4021-b603-78f168e3af2f.jpg)

**Comment by stevekamps** [comment]
remove space

**Comment by stevekamps** [comment]
![IMG_9973](https://user-images.githubusercontent.com/77851393/151586369-de7d2906-b88d-45e2-9279-d0857cebee82.jpg)

**Comment by stevekamps** [comment]
remove space

**Comment by stevekamps** [comment]
![IMG_9969](https://user-images.githubusercontent.com/77851393/151586418-790b0d0f-7592-4942-a1ac-4a4ac5e4d0e2.jpg)
Add a space

**Comment by stevekamps** [comment]
![IMG_9970](https://user-images.githubusercontent.com/77851393/151586461-f6768950-d042-4b7f-a031-d4e6f1cb10f8.jpg)

**Comment by stevekamps** [comment]
remove spaces

**Comment by stevekamps** [comment]
![IMG_9971](https://user-images.githubusercontent.com/77851393/151586488-d12199a6-4013-40fa-babc-33d3b015f42c.jpg)

**Comment by stevekamps** [comment]
remove space

**Comment by stevekamps** [comment]
![IMG_9972](https://user-images.githubusercontent.com/77851393/151586516-236e9d9f-75a0-46b6-8ec6-62aa614b60f8.jpg)

**Comment by stevekamps** [comment]
remove space

**Comment by technicalbirdVayuz** [comment]
@stevekamps As the content in About us page is coming from the Editor, there will be library CSS that will conflict with the home page css, Exact match may not be possible

> We need the About us to look like the homepage. As you can see they are different

**Comment by technicalbirdVayuz** [comment]
For Space Issues, Please share the content in document, we will  update it from the backend & then you can check

**Comment by stevekamps** [comment]
[Volleyball Unite Privacy.Final- USA.docx](https://github.com/technicalbirdVayuz/volleyball-unite-usa-issue-tracker/files/7960510/Volleyball.Unite.Privacy.Final-.USA.docx)

**Comment by stevekamps** [comment]
[Volleyball Unite Terms.Final - USA.docx](https://github.com/technicalbirdVayuz/volleyball-unite-usa-issue-tracker/files/7960512/Volleyball.Unite.Terms.Final.-.USA.docx)

**Comment by stevekamps** [comment]
I did manually go through the backoffic dashboard and remove all spaces etc. but it doesnt appear to update on the volleyballunite.com website

**Comment by stevekamps** [comment]
Please use these. I have tried to fix all the spacing in these

[Volleyball Unite Privacy.Final- USA.docx](https://github.com/technicalbirdVayuz/volleyball-unite-usa-issue-tracker/files/7960545/Volleyball.Unite.Privacy.Final-.USA.docx)
[Volleyball Unite Terms.Final - USA.docx](https://github.com/technicalbirdVayuz/volleyball-unite-usa-issue-tracker/files/7960547/Volleyball.Unite.Terms.Final.-.USA.docx)

**Comment by technicalbirdVayuz** [comment]
This is how it is coming, Can you share final doc without having strikes

![image](https://user-images.githubusercontent.com/18699624/151648414-30cf97d8-36b1-4175-8203-c3e71fb0eae9.png)

**Comment by stevekamps** [comment]
In the word document go to the Review tab at the top of word banner.  Then choose no markup from the dropdown menu

**Comment by vayuzpriya** [comment]
"b" added in end of T&C.

**Comment by vayuzpriya** [comment]
> ![aboutus](https://user-images.githubusercontent.com/77851393/151584950-d3ef0a5e-9da7-4f9d-9926-b27195cf66aa.jpg) ![homepage](https://user-images.githubusercontent.com/77851393/151584956-97fbde99-59e2-4c50-a60f-69b9f2afd0af.jpg)

Fixed

**Comment by rgnarok** [comment]
This is fixed
